name: vulnerable-secret

run-name: "${{ github.event.issue.actor }} flag check"

on:
  issues:
    types: 
      - opened

jobs:
  delete_issue:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs: #creating outputs that can be used by the second job
      title: ${{ steps.title.outputs.title }}
      body: ${{ steps.body.outputs.body }}     
    env:
      title: ${{ github.event.issue.title }}
      body: ${{ github.event.issue.body }}
    steps:
      - id: title
        run: |
          echo "title=$title" >> "$GITHUB_OUTPUT"  #transfering user inputs to the outputs so they can be run in an environment without permissions
          
      - id: body
        run: |
          echo "body=$body" >> "$GITHUB_OUTPUT"
          
      - name: delete issue
        env:
          GH_TOKEN: ${{ secrets.pat }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql \
            -f query='
              mutation($id:ID!) {
                deleteIssue(input:{issueId:$id}) {
                  clientMutationId
                }
              }
            ' \
            -F id="$ISSUE_ID"



  check_flag:
    permissions: {}
    needs: delete_issue
    runs-on: ubuntu-latest
    container:
      image: ubuntu:24.04
    env:
      flag: ${{ secrets.flag }}
      encrypt_key: ${{ needs.delete_issue.outputs.title }}
    steps:
      - name: place
        env:
          pat: patrick
        run: echo "pat"
        
      - name: store issue body
        run: echo ${{ needs.delete_issue.outputs.body }} > flag.txt
        
      - name: flag check
        run: |
          if grep -q "$flag" "title.txt"; then
            echo "Now you are ready for the next step - ${{ secrets.next_step }}" > flag.txt
          else
            echo " is a nice try but you aren't ready for what's next." >> flag.txt
          fi
              
      - name: encrypt 
        run: |
          if [ -n "$encrypt_key" ]; then
              gpg --symmetric \
                  --cipher-algo AES256 \
                  --batch \
                  --yes \
                  --pinentry-mode loopback \
                  --passphrase "$encrypt_key" \
                  flag.txt
          fi
              
      - uses: actions/upload-artifact@v7 #upload a compressed version of the encrypted file to the workflow run entry (find the entries at https://github.com/LungaFermata/Pecan/actions)
        with:
          name: flag
          path: flag.txt.gpg
          retention-days: 1
