name: flag_check

run-name: "${{ github.actor }} flag check"

on:
  issues:
    types: 
      - opened

jobs:
  delete_issue:
    permissions: write-all
    runs-on: ubuntu-latest
    outputs: 
      title: ${{ steps.title.outputs.title }}
      body: ${{ steps.body.outputs.body }}     
    env:
      title: ${{ github.event.issue.title }}
      body: ${{ github.event.issue.body }}
    steps:
      - id: title
        run: |
          {
            echo 'title<<EOF'
            printf '%s\n' "$title"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          
      - id: body
        run: |
          {
            echo 'body<<EOF'
            printf '%s\n' "$body"
            echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          
      - name: delete issue
        env:
          GH_TOKEN: ${{ secrets.pat }}
          ISSUE_ID: ${{ github.event.issue.node_id }}
        run: |
          gh api graphql \
            -f query='
              mutation($id:ID!) {
                deleteIssue(input:{issueId:$id}) {
                  clientMutationId
                }
              }
            ' \
            -F id="$ISSUE_ID"



  check_flag:
    permissions: {}
    needs: delete_issue
    runs-on: ubuntu-latest
    env:
      flag: ${{ secrets.flag }}
      encrypt_key: ${{ needs.delete_issue.outputs.title }}
    steps:
      - name: store issue body
        run: echo ${{ needs.delete_issue.outputs.body }} > flag.txt
        
      - name: flag check
        run: |
          if grep -q "$flag" "flag.txt"; then
            echo "Now you are ready for the next step - ${{ secrets.next_step }}" > flag.txt
          else
            echo " is a nice try but you aren't ready for what's next." >> flag.txt
          fi
              
      - name: encrypt 
        run: |
          if [ -n "$encrypt_key" ]; then
              gpg --symmetric \
                  --cipher-algo AES256 \
                  --batch \
                  --yes \
                  --pinentry-mode loopback \
                  --passphrase "$encrypt_key" \
                  flag.txt
          fi
              
      - uses: actions/upload-artifact@v7
        with:
          name: flag
          path: flag.txt.gpg
          retention-days: 1
